name: 'sales_demo_pipeline'
version: '1.0.0'
config-version: 2

profile: 'sales_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sales_demo_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table

on-run-start: "{{ execute_create_schemas() }}"
