version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ebury_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ebury_network

  airflow-webserver:
    image: ebury-airflow:latest
    container_name: ebury_airflow_webserver
    build:
      context: .
      dockerfile: Dockerfile
    command: airflow webserver
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres:5432/${POSTGRES_DB:-airflow}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY:-Nx8_A9Lr3gH8xK0dFvWpQjZm4nB7cE2rT5sU6vX9yZ}
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_HOST: postgres
      POSTGRES_DB: ebury_analytics
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data/customer_transactions.csv:/opt/airflow/data/customer_transactions.csv
      - ./dbt:/opt/dbt
      - airflow_logs:/opt/airflow/logs
    networks:
      - ebury_network
    restart: unless-stopped

  airflow-scheduler:
    image: ebury-airflow:latest
    container_name: ebury_airflow_scheduler
    build:
      context: .
      dockerfile: Dockerfile
    command: airflow scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres:5432/${POSTGRES_DB:-airflow}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_HOST: postgres
      POSTGRES_DB: ebury_analytics
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data/customer_transactions.csv:/opt/airflow/data/customer_transactions.csv
      - ./dbt:/opt/dbt
      - airflow_logs:/opt/airflow/logs
    networks:
      - ebury_network
    restart: unless-stopped

volumes:
  postgres_data:
  airflow_logs:

networks:
  ebury_network:
    driver: bridge
